apiVersion: backstage.io/v1beta2
kind: Component
metadata:
  name: {{cookiecutter.component_id | jsonify}}
  description: {{cookiecutter.description | jsonify}}
  annotations:
    github.com/project-slug: {{cookiecutter.destination.git.owner + "/" + cookiecutter.destination.git.name}}
    backstage.io/techdocs-ref: url:{{cookiecutter.storePath}}
    argocd/app-name: {{cookiecutter.component_id | jsonify}}
    backstage.io/kubernetes-id: {{cookiecutter.component_id | jsonify}}
spec:
  type: service
  lifecycle: experimental
  owner: {{cookiecutter.owner | jsonify}}
