create-argocd-application:
    script: |
          curl -v -k --fail --location \
          --request POST '{{cookiecutter.argocd_url}}/api/v1/applications' \
          --header 'Content-Type: application/json' \
          --header 'Cookie: argocd.token={{cookiecutter.argocd_token}}' \
          --data-raw '{
              "metadata": {
                  "name": "{{cookiecutter.component_id}}"
              },
              "spec": {
                  "source": {
                      "repoURL": "{{cookiecutter.storePath}}.git",
                      "path": "charts/"
                  },
                  "destination": {
                      "namespace": "{{cookiecutter.component_id}}",
                      "server": "https://kubernetes.default.svc"
                  },
                  "syncPolicy": {
                      "syncOptions": [
                          "CreateNamespace=true"
                      ],
                      "automated": {
                          "allowEmpty": true,
                          "prune": false,
                          "selfHeal": false
                      }
                  }
              }
          }'
